28 res tful routes
WildCodeSchool/hdrain-api-lyon-js-react-march21 pull request #34
Opened 2021-06-23 14:08 UTC by hkamalo

2021-06-24 15:35 UTC, edouardmisset requested changes
Good job. It works :)
For the naming conversion, check this : 
https://restfulapi.net/resource-naming/

2021-06-24 15:35 UTC, edouardmisset commented on .gitignore
> +upload
```suggestion
storage
```

2021-06-24 15:35 UTC, edouardmisset commented on models/ExperimentModel.js
> +const findMany = () => prisma.experiment.findMany();
Pas sûr de comprendre l'utilité de récupérer toutes les expériences ?

2021-06-24 15:35 UTC, edouardmisset commented on routes/experiments.js
> +experimentsRouter.get('/all', async (req, res) => {
Pourquoi /all ??
https://restfulapi.net/resource-naming/
```suggestion
experimentsRouter.get('/', async (req, res) => {
```

2021-06-24 15:35 UTC, edouardmisset commented on routes/experiments.js
> +experimentsRouter.get('/:experimentsId', async (req, res) => {
```suggestion
experimentsRouter.get('/:experimentId', async (req, res) => {
```

2021-06-24 15:35 UTC, edouardmisset commented on routes/experiments.js
> +    const {experimentsId} = req.params;
```suggestion
    const {experimentId} = req.params;
```

2021-06-24 15:35 UTC, edouardmisset commented on routes/experiments.js
> +    const experiment = await ExperimentModel.findOne(experimentsId);
```suggestion
    const experiment = await ExperimentModel.findOne(experimentId);
```

2021-06-24 15:35 UTC, edouardmisset commented on routes/experiments.js
> +experimentsRouter.post('/create', async (req, res) => {
Il me semble que dans le cours de API Restful, c'est comme ça :
https://restfulapi.net/resource-naming/
```suggestion
experimentsRouter.post('/', async (req, res) => {
```

2021-06-24 15:35 UTC, edouardmisset commented on routes/locations.js
> +locationsRouter.get('/all', async (req, res) => {
```suggestion
locationsRouter.get('/', async (req, res) => {
```

2021-06-24 15:35 UTC, edouardmisset commented on routes/locations.js
> +    const {locationId} = req.params;
ok 😂

2021-06-24 15:35 UTC, edouardmisset commented on routes/sensors.js
> +sensorsRouter.get('/all', async (req, res) => {
```suggestion
sensorsRouter.get('/', async (req, res) => {
```

2021-06-24 15:35 UTC, edouardmisset commented on routes/sensors.js
> +sensorsRouter.post('/create', async (req, res) => {
```suggestion
sensorsRouter.post('/', async (req, res) => {
```

2021-06-24 15:35 UTC, edouardmisset commented on routes/users.js
> +usersRouter.get('/all', async (req, res) => {
```suggestion
usersRouter.get('/', async (req, res) => {
```

2021-06-24 15:35 UTC, edouardmisset commented on routes/users.js
> +usersRouter.post('/create', async (req, res) => {
```suggestion
usersRouter.post('/', async (req, res) => {
```

2021-06-25 12:14 UTC, hkamalo commented on .gitignore
> +upload
changes has been made

2021-06-25 12:14 UTC, hkamalo commented on models/ExperimentModel.js
> +const findMany = () => prisma.experiment.findMany();
élément déjà présent sur dev

2021-06-25 12:15 UTC, hkamalo commented on routes/experiments.js
> +experimentsRouter.get('/all', async (req, res) => {
changements fait

2021-06-25 12:16 UTC, hkamalo commented on routes/experiments.js
> +experimentsRouter.get('/:experimentsId', async (req, res) => {
changements fait

2021-06-25 12:20 UTC, hkamalo commented
All request changes has been taken

2021-06-25 12:24 UTC, edouardmisset approved these changes
All good ! 
Nice job 👍

2021-06-25 12:28 UTC, So-G approved these changes
check ! new routes work

2021-06-25 12:28 UTC, merged